import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin/catppuccin-latte.toml"
  #"~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "SpaceMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = -10

[window]
decorations = "Full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 30

[window.padding]
x = 10
y = 10
